<?php

namespace Drupal\custom_migrate\Plugin\migrate\source;

use Drupal\migrate\Event\MigrateRollbackEvent;
use Drupal\migrate\Plugin\migrate\source\SqlBase;
use Drupal\migrate\Row;

/**
 *  Extract users from Mysql database.
 *
 * @MigrateSource(
 *   id = "custom_node"
 * )
 */
class Node extends SqlBase {

  public function query() {
	$query = $this->select('node', 'n')
      ->fields('n', [
          'nid',
          'type',
          'uid',
          'title',
          'created',
		  'changed',
        ])
	 ->fields('p', [
          'field_place_value',
        ])
	 ->fields('b', [
          'body_value',
        ])
	 ->fields('d', [
          'field_date_value',
        ])
	 ->fields('t', [
          'field_time_value',
        ])
	 ->innerJoin('field_data_body', 'b', 'b.entity_id = n.nid')
	 ->innerJoin('field_data_field_place', 'p', 'p.entity_id = n.nid')
	 ->innerJoin('field_data_field_date', 'd', 'd.entity_id = n.nid')
	 ->innerJoin('field_data_field_time', 't', 't.entity_id = n.nid')
	 ->condition('n.type', 'test');
    return $query;
  }

  public function fields() {
    $fields = [
		'nid' => $this->t('nid'),
		'type' => $this->t('type'),
		'uid' => $this->t('uid'),
		'title' => $this->t('title'),
		'created' => $this->t('created'),
		'changed' => $this->t('changed'),
		'body_value' => $this->t('body_value'),
		'field_place_value' => $this->t('field_place_value'),
		'field_date_value' => $this->t('field_date_value'),
		'field_time_value' => $this->t('field_time_value'),
    ];

    return $fields;
  }

  public function getIds() {
    return [
      'nid' => [
        'type' => 'integer',
        'alias' => 'nid',
      ],
    ];
  }

  public function prepareRow(Row $row) {
    $date = $row->getSourceProperty('field_date_value');
    $time = $row->getSourceProperty('field_time_value');
    $datetime = $date . 'T' . $time . ':00';
    $row->setSourceProperty('date', $datetime);
    return parent::prepareRow($row);
  }

  public function preRollback(MigrateRollbackEvent $event) {
    //parent::preRollback($event); // TODO: Change the autogenerated stub
  }

  public function postRollback(MigrateRollbackEvent $event) {
    //parent::postRollback($event); // TODO: Change the autogenerated stub
  }

}